[build]
  command = "npm run build"
  publish = "dist/"

[dev]
  command = "npm run dev"
  port = 5173  # ou le port que vous utilisez en développement

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
