services:
  - type: web
    name: red-product-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://red-product-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: red-product-youssuf9900-54bf.k.aivencloud.com
      - key: DB_PORT
        value: "21188"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false  # À définir manuellement dans le tableau de bord Render
      - key: DB_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "true"
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
